#!/bin/bash

export PS1="\w \\$ "

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='grep -r --color=auto'

alias ll='ls -l'
alias la='ls -A'
alias lt='ls -lrt'

alias c='set -f; perl -le "print eval qq(@ARGV); set +f"'

export EDITOR=/usr/bin/vim
alias e="$EDITOR"

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
